spring.application.name=final-web-2

server.port=8080

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:5432/${PGDATABASE:productcrud}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Profile images (disajikan lewat /uploads/profiles/**)
app.upload.profiles-dir=uploads/profiles
