spring.application.name=product-crud

# PostgreSQL Database Configuration using environment variables
spring.datasource.url=jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Profile images (folder dibuat otomatis saat startup)
app.upload.profiles-dir=uploads/profiles